### PR TITLE
Modify the family table naming scheme

### PR DESCRIPTION
**Pull request by mandel59**
Fixed as described in [Font Info & Metadata](http://designwithfontforge.com/en-US/Font_Info_&_Metadata.html)

### CODE REVIEW

**Comment by rayshan** [comment]
Thanks @mandel59! You are awesome.

@davelab6 can you please review? Or let me know how I can help to review.

**Comment by rayshan** [comment]
@mandel59 I've added you as a collaborator to this repo.

**Comment by davelab6** [comment]
Sorry my delay in this, hope to get to M+ fonts later this year!

**Comment by rayshan** [comment]
No worries @davelab6, let us know how we can help :)

**Pull request merged**
